baseURL = "https://1look4.github.io/bloog"
languageCode = "en-us"
title = "Gopinath's personal homepage"
paginate = 20

[params]
subtitle = "Write and Teach on tech, business, and life"
thumbnail = "thumb.jpg"

[taxonomies]
   tag = "tags"
   author = "authors"

[menu]
   [[menu.header]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 1

   [[menu.header]]
      identifier = "musings"
      name = "Blog"
      url = "/blog"
      weight = 2
